### ISSUE TITLE
New API Key for DIP API

### ISSUE THREAD

**Issue by hejjoe** [simonwoerpel/bundestag-dip-memorious#1]
The old key is used here: https://github.com/simonwoerpel/bundestag-dip-memorious/blob/main/src/bundestag_dip.yml#L10

> Zur Nutzung ist ein API-Key notwendig. Der zunächst bis Ende Mai 2023 gültige API-Key lautet:
> GmEPb1B.bfqJLIhcGAsH9fTJevTglhFpCoZyAAAdhp
> 
> Auf Anfrage können Sie auch einen eigenen API Key erhalten, der zeitlich unbefristet ist.
> 
> Bitte stellen Sie eine diesbezügliche Anfrage per E-Mail an: parlamentsdokumentation@bundestag.de

https://dip.bundestag.de/%C3%BCber-dip/hilfe/api#content

**Comment by simonwoerpel** [comment]
thx, api key is updated now to the new public one
